export {default as Home} from "./Home"
export {default as Cart} from "./Cart"
export {default as Login} from "./Login"
export {default as SignUp} from "./SignUp"
export {default as History} from "./History"
export {default as Bill} from "./Bill"
export {default as Account} from "./Account"